name: Staging Deploy

on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
        
    - name: FTP Deploy to WP Engine (Staging)
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://109.234.160.108
        ftp-username: siyw9232@dashboard-impulsion.com
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        
